version: "3.9"

services:

  back:
    init: true
    container_name: back
    ports:
      - "3000:3000"
    depends_on:
      - db
    build:
      context: ./project/back
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - networksjob
    restart: unless-stopped

  front:
    init: true
    container_name: front
    depends_on:
      - back
    build:
      context: ./project/front
    networks:
      - networksjob
    restart: unless-stopped
    ports:
      - "8080:8080"

  db:
    init: true
    container_name: db
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - networksjob
    ports:
      - "5432:5432"

  adminer:
    container_name: adminer
    image: adminer
    restart: unless-stopped
    ports:
      - "3215:8080"
    networks:
      - networksjob

      
volumes:
  db_data:

networks:
  networksjob:
